FROM python:3.10-slim

WORKDIR /app

COPY requirements-rasa.txt /app/requirements-rasa.txt

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements-rasa.txt

COPY . /app

RUN mkdir -p /app/models

CMD ["rasa", "run", "--enable-api", "--cors", "*", "--port", "5005", "--credentials", "credentials.yml", "--endpoints", "endpoints.docker.yml"]