FROM python:3.10-slim
WORKDIR /app
COPY requirements-actions.txt .
RUN pip install --no-cache-dir -r requirements-actions.txt
COPY actions ./actions
CMD ["python", "-m", "rasa_sdk", "--actions", "actions", "--port", "5055"]
